version: '3.9'
services:
  mysql:
    image: mysql:8.0.3
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test  # 변경 가능한 비밀번호로 설정
      MYSQL_DATABASE: final
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  spring-crud-example:
    build:
      context: ..
      dockerfile: BACKEND/Dockerfile
    container_name: container_app
    links:
      - mysql
    #    restart: always
    ports:
      - "8761:8761"
    tty: true
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/final?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test